name: upload-p5-image

on:
  push:
    branches:
      - master
    paths:
      - "p5/**"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push P5 Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}
          repository: eecs485/p5
          tags: latest
          path: "p5"
          cache_froms: eecsautograder/ubuntu18:latest,eecs485/ag_base:latest,eecs485/p5:latest
