# Automated pipeline for building and uploading autograder container images to Docker Hub.
#
# Jad Chaar <jadchaar@umich.edu>

name: upload-ag-images

on:
  push:
    branches:
      - master

jobs:
  upload-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}

      # Only rebuild if base image has changed
      - name: Build and push base Docker image
        uses: docker/build-push-action@v2
        with:
          context: base
          tags: eecs485/ag_base:latest
          push: true

  upload-p1:
    needs: upload-base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}

      # Only rebuild if base or p1 image has changed
      - name: Build and push p1 Docker image
        uses: docker/build-push-action@v2
        with:
          context: p1
          tags: eecs485/p1:latest
          push: true

  upload-p2:
    needs: upload-base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}

      # Only rebuild if base or p2 image has changed
      - name: Build and push p2 Docker image
        uses: docker/build-push-action@v2
        with:
          context: p2
          tags: eecs485/p2:latest
          push: true

  upload-p3:
    needs: upload-base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}

      # Only rebuild if base or p3 image has changed
      - name: Build and push p3 Docker image
        uses: docker/build-push-action@v2
        with:
          context: p3
          tags: eecs485/p3:latest
          push: true

  upload-p4:
    needs: upload-base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}

      # Only rebuild if base or p4 image has changed
      - name: Build and push p4 Docker image
        uses: docker/build-push-action@v2
        with:
          context: p4
          tags: eecs485/p4:latest
          push: true

  upload-p5:
    needs: upload-base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}

      # Only rebuild if base or p5 image has changed
      - name: Build and push p5 Docker image
        uses: docker/build-push-action@v2
        with:
          context: p5
          tags: eecs485/p5:latest
          push: true
