name: upload-base-image

on:
  push:
    branches:
      - master
    paths:
      - "base/**"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}
          repository: eecs485/ag_base
          tags: latest
          path: "base"
          cache_froms: eecs485/ag_base:latest,eecsautograder/ubuntu18:latest
